import { bibliography } from '../bibliography';
import type { ToolLocaleContent } from '../../../types';
import type { InteractiveFlashcardGeneratorUI } from '../index';

const slug = 'interactive-flashcard-generator' as const;
const title = 'Interactive Flashcard Generator & Study Deck';
const description = 'Boost your study sessions with active recall and spaced repetition. Create custom flashcards, study with 3D card flips, score difficulty, and export/import decks.';

const faqItems = [
  { question: 'What is active recall?', answer: 'Active recall is a learning principle that involves testing your memory by actively retrieving information, rather than passively reviewing or reading notes.' },
  { question: 'How does spaced repetition work?', answer: 'Spaced repetition is a method where you review difficult cards more frequently and easy cards less frequently over increasing intervals of time to optimize retention.' },
  { question: 'How can I save my custom flashcards?', answer: 'You can export your deck as a JSON file. To resume studying later, simply click the Import button and upload that file.' },
  { question: 'What do the Easy, Medium, and Hard scores do?', answer: 'They help you categorize how well you remembered the card. In a full Leitner system, cards categorized as Hard are reviewed more often to strengthen neural pathways.' },
];

const howToItems = [
  { name: 'Create a Card', text: 'Enter the question or concept on the Front field and the answer or explanation on the Back field, then click Add Card.' },
  { name: 'Review the Deck', text: 'Click on any card in the viewer box to flip it and reveal the answer.' },
  { name: 'Score Your Memory', text: 'Assess how easily you recalled the answer using the Easy, Medium, or Hard buttons.' },
  { name: 'Save Your Study Session', text: 'Use the Export button to download your custom deck so you can load it back later.' },
];

const faqSchema = {
  '@context': 'https://schema.org' as const,
  '@type': 'FAQPage' as const,
  mainEntity: faqItems.map((item) => ({
    '@type': 'Question' as const,
    name: item.question,
    acceptedAnswer: { '@type': 'Answer' as const, text: item.answer },
  })),
};

const howToSchema = {
  '@context': 'https://schema.org' as const,
  '@type': 'HowTo' as const,
  name: title,
  description,
  step: howToItems.map((step) => ({
    '@type': 'HowToStep' as const,
    name: step.name,
    text: step.text,
  })),
};

const appSchema = {
  '@context': 'https://schema.org' as const,
  '@type': 'SoftwareApplication' as const,
  name: title,
  description,
  applicationCategory: 'EducationalApplication' as const,
  operatingSystem: 'Web' as const,
  offers: { '@type': 'Offer' as const, price: '0', priceCurrency: 'USD' },
};

export const content: ToolLocaleContent<InteractiveFlashcardGeneratorUI> = {
  slug,
  title,
  description,
  ui: {
    cardCreator: 'Flashcard Creator',
    questionLabel: 'Front (Question)',
    answerLabel: 'Back (Answer)',
    addCard: 'Add Flashcard',
    questionPlaceholder: 'e.g., What is the capital of France?',
    answerPlaceholder: 'e.g., Paris',
    reviewMode: 'Study Session',
    cardIndex: 'Card',
    flipCard: 'Click to flip',
    nextCard: 'Next',
    prevCard: 'Previous',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    resetSession: 'Reset Progress',
    importExport: 'Deck Management',
    importDeck: 'Import JSON',
    exportDeck: 'Export JSON',
    exportSelected: 'Export Selected',
    exportAll: 'Export All Decks',
    emptyDeckWarning: 'Your deck is empty. Create a card or import a deck to start studying.',
    sampleQuestion1: 'What is active recall?',
    sampleAnswer1: 'A learning technique that involves actively stimulating memory retrieval during the learning process.',
    sampleQuestion2: 'Who formulated the forgetting curve hypothesis?',
    sampleAnswer2: 'Hermann Ebbinghaus, who studied the exponential nature of forgetting information over time.',
    aiPromptGenerator: 'AI Flashcard Assistant',
    aiTopicsLabel: 'Enter your exam topics or notes',
    aiTopicsPlaceholder: 'e.g., Math exam covering Derivatives, Integrals and Limits...',
    generatePromptBtn: 'Generate AI Prompt',
    aiPromptOutputLabel: 'Copy this prompt to ChatGPT/Gemini',
    copyPromptBtn: 'Copy to Clipboard',
    selectAll: 'Select All',
    deleteCategory: 'Delete Category',
    deleteConfirmMsg: 'Are you sure you want to delete this category and all its cards?',
    cancel: 'Cancel',
    delete: 'Delete',
    pasteJsonTitle: 'Paste Flashcard JSON',
    pasteJsonPlaceholder: 'Paste the JSON generated by AI here...',
    importBtn: 'Import',
    aiPromptTemplate: 'Act as an educational assistant. Generate a set of flashcards for the following topics:\n"{topics}"\n\nOutput the result formatted inside a single markdown code block with the "json" language identifier (using triple backticks) so it is easy to copy. Do not include any other markdown text outside the code block. Use this exact structure:\n```json\n{\n  "categories": ["Math Exam"],\n  "deck": [\n    {\n      "question": "[Flashcard Front / Question]",\n      "answer": "[Flashcard Back / Answer]",\n      "category": "Math Exam",\n      "score": null\n    }\n  ]\n}\n```',
  },
  seo: [
    { type: 'title', text: 'Optimize Your Study Strategy with Active Recall and Spaced Repetition', level: 2 },
    { type: 'paragraph', html: 'Flashcards are widely recognized as one of the most effective tools for memorization and long-term retention. By combining active retrieval with a structured scoring flow, you can pinpoint your weak areas, review efficiently, and retain information far longer than passive study methods.' },
    { type: 'title', text: 'Active Recall vs. Passive Learning Methods', level: 3 },
    { type: 'paragraph', html: 'Many students rely on passive review techniques like highlighting text or re-reading textbooks. While these methods feel productive, cognitive science shows they create an illusion of competence. True learning happens when you force your brain to retrieve the information.' },
    { type: 'table', headers: ['Study Method', 'Cognitive Engagement', 'Retention Rate', 'Best Suited For'], rows: [
      ['Interactive Flashcards', 'High (Active Recall)', 'Excellent', 'Vocabulary, formulas, key concepts, dates.'],
      ['Summarizing Text', 'Medium (Synthesis)', 'Moderate', 'Understanding complex narratives and arguments.'],
      ['Re-reading Notes', 'Low (Passive Review)', 'Poor', 'Initial exposure to new materials.'],
    ] },
    { type: 'title', text: 'The Pros and Cons of Flashcard-Based Learning', level: 3 },
    {
      type: 'proscons',
      title: 'Comparing Flashcards Benefits and Limitations',
      items: [
        { pro: 'Forces active mental retrieval instead of passive recognition.', con: 'Can be time-consuming to create initially.' },
        { pro: 'Identifies exact knowledge gaps immediately.', con: 'Not ideal for deep comprehension of highly complex arguments.' },
        { pro: 'Highly portable and customizable for any subject or exam.', con: 'Requires regular study discipline to reap spaced repetition benefits.' }
      ]
    },
    { type: 'title', text: 'How to Write Effective Study Decks', level: 3 },
    { type: 'tip', html: '<strong>Rule of One:</strong> Each flashcard should test exactly one question or one concept. Avoid writing paragraphs on the back. If a card is too complex, break it down into three or four smaller, bite-sized cards.' },
    { type: 'title', text: 'Key Terms and Methodologies', level: 3 },
    { type: 'glossary', items: [
      { term: 'Active Recall', definition: 'The process of actively testing your memory by retrieving answers, forcing neural pathways to strengthen.' },
      { term: 'Spaced Repetition', definition: 'A learning technique where cards are reviewed at increasing intervals of time to prevent forgetting.' },
      { term: 'Leitner System', definition: 'A method of grouping flashcards into boxes based on review history, prioritizing harder cards.' },
      { term: 'Forgetting Curve', definition: 'The mathematical representation of the exponential rate at which information is forgotten after initial learning.' },
    ] },
    { type: 'title', text: 'AI-Powered Flashcard Creation', level: 3 },
    { type: 'paragraph', html: 'Creating study decks manually can be tedious. With our integrated <strong>AI Flashcard Assistant</strong>, you can instantly turn plain syllabus notes or textbook outlines into ready-to-import flashcard decks. Simply describe your exam topics, click "Generate AI Prompt," copy the generated instructions, and paste them into any AI model (like ChatGPT, Gemini, or Claude). The AI will structure the cards in the exact JSON format needed for importing.' },
    { type: 'title', text: 'Flexible Collaborative Studying: Selective Sharing and Merging', level: 3 },
    { type: 'paragraph', html: 'Studying in groups is more productive when you divide and conquer. Our deck manager lets you export only the categories you choose. When a classmate imports your file, the system dynamically <strong>merges</strong> the new categories and cards with their existing local deck instead of overwriting their data, preventing any loss of study history.' },
    { type: 'title', text: 'Summary of Best Practices', level: 3 },
    { type: 'summary', items: [
      'Create custom categories to organize study decks for specific exams or modules.',
      'Review your cards daily or weekly, marking them accurately as Easy, Medium, or Hard.',
      'Export and backup your decks regularly to avoid losing progress.',
      'Share exported decks with classmates to collaborate on exam preparation.'
    ] }
  ],
  faq: faqItems,
  howTo: howToItems,
  bibliography,
  schemas: [faqSchema, howToSchema, appSchema],
};
